### ISSUE TITLE
Utils.updateCustomer(...)

### ISSUE THREAD

**Issue by cyw617** [cyw617/taxi#15]
There is a bug in Utils.updateCustomer(...).

Line 89 - 93

> ```
>   if (customer.getRegDate() != null) {
>       Utils.putPreference(context, Utils.PREFS_REGDATE_KEY, customer.getRegDate().toString());
>   } else {
>       Utils.putPreference(context, Utils.PREFS_REGDATE_KEY, "");
>   }
> ```

Since DateTime is not a normal String, it should not be saved as an empty string (Ln 92) if its value is null.

**Comment by cyw617** [comment]
@byronyi 
I don't know how to solve it, because there are two ways to eliminate the bug, and I am not sure with the consequence of each method.
1. replace the empty string by null
2. simple do not save a null RegDate into the sharedPreference

**Comment by cyw617** [comment]
By the way, should "Device ID" be included in updateCustomer?

**Comment by cyw617** [comment]
I have eliminated the bug by replacing the empty string by null.
Please correct me if this is inappropriate.

**Comment by byronyi** [comment]
I think we will know once we start to implement GCM part. Let's see where it will go
