### ISSUE TITLE
Test cases in Customer

### ISSUE THREAD

**Issue by ZeroGazer** [cyw617/taxi#18]
During testing in Jenkins, I found that testing kept busy in either following class and it could not proceed to next stage.

```
 comp3111h.anytaxi.customer.test.MainActivityTest
 comp3111h.anytaxi.customer.test.MoreOptionTest
```

Can you guys fix them ASAP? Because we have to submit test coverage report on Monday.

**Comment by byronyi** [comment]
I'm on this.

**Comment by byronyi** [comment]
Is there any requirements on the coverage? Or we just need to submit a report?

**Comment by ZeroGazer** [comment]
JC:
Regarding test case coverage, 70% of block coverage is a guideline and you
can reach to it gradually by the final presentation.

**Comment by byronyi** [comment]
This is resolved. Please contribute on test cases now. Take a look on my test cases on <code>MainActivity</code> and <code>LoginActivity</code> for example.
