### ISSUE TITLE
Test Cases on Customer: Register Activity!

### ISSUE THREAD

**Issue by byronyi** [cyw617/taxi#25]
As our work on customer part is finishing, it's time to write more test cases. Currently we can only cover about 20% percent overall, but a few test cases can raise your class' block coverage to more than 60%! 

<url>http://pishon.cse.ust.hk:8181/job/AnyTaxi/ws/TaxiClient/AnyTaxi_Customer_Test/bin/_files/1c.html</url>
<url>http://pishon.cse.ust.hk:8181/job/AnyTaxi/ws/TaxiClient/AnyTaxi_Customer_Test/bin/_files/1b.html</url>

This would not be hard for you guys to reach 70%. Let's get started now!

If you have no idea how to write test cases, you can find examples of my test cases, residing in <code>AnyTaxi_Customer_Test/src</code>.

**Comment by byronyi** [comment]
To reduce the workload, let's write the first test case on <code>RegisterActivity</code>. This is taken cared by @cyw617.

Close this issue once test case is ready.

**Comment by cyw617** [comment]
I have commited the test cases for RegisterActivity (not 100% covered).
Now, we need to wait for @johcnhung to fix Issue #31 in order to check the coverage.

**Comment by cyw617** [comment]
@byronyi 
Important Note:
To generate positive test case for successful registration, a new user (with random email, ending with @anytaxi.hk) will be pushed to the database, for every run of the test case.

**Comment by cochung08** [comment]
oh my god, I forgot to commit the deleteorder class.

so okay now?

**Comment by byronyi** [comment]
@cyw617 this is brilliant. Do we have local coverage for your test cases? ci-server is down for a whole day.

**Comment by cyw617** [comment]
@byronyi I don't know how to generate local coverage, and I am not available tonight......Can you do it for me? The server is down for more than 24 hours.

Tell me if the coverage is too low. I didn't test all the branches for validating user input, which is tedious.
(but I guess those branches would not boost the coverage a lot)

**Comment by byronyi** [comment]
I  am doing it now. I will push the coverage report on to github.
Again, good job! Take a rest, we have more to do this weekend.

**Comment by ZeroGazer** [comment]
now the block coverage of customer is 38%

**Comment by byronyi** [comment]
Fantastic. You reaches average 90% of coverage and this increase our overall coverage to 37%! This is indeed a great job.

Take a good rest.

@Tony-Mao @ywangbc @johcnhung @chpoon92 Come and appreciate Tim's work.

**Comment by cyw617** [comment]
Thanks for your appreciation. I just follow your guideline.
It will be a harsh weekend. Let's work hard together :)
