### ISSUE TITLE
Application stops when clicked AnyTaxi button in Request Activity

### ISSUE THREAD

**Issue by hongzimao** [cyw617/taxi#34]
When clicking on the red AnyTaxi button, application is stopped. And the bug is could not find onClick handler. 

@byronyi did you link sending request to server with that button onClick function? There was a function to redirect to next activity but now it is gone. Thanks.

**Comment by ywangbc** [comment]
The problem has been fixed. I am going to add a transition window from
request activity to tracking activity now

2014-05-01 16:15 GMT+08:00 Tony Mao notifications@github.com:
