### ISSUE TITLE
Register

### ISSUE THREAD

**Issue by cyw617** [cyw617/taxi#9]
#### ABSTRACT

Create a new activity to deal with unregistered user.
#### DESIGN

It will include two "fragments" (possibly).
The first fragment requests the user to agree with the agreement.
The second fragment requests the user to input information.
An "exit" dialog will be shown if the user press back button at any stage.
#### FLOW
1. MainActivity -> No email found in the default sharedPreference
2. LoginActivity -> Server does not have the record for the picked account
3. RegisterActivity
   - display the fragment for agreement
   - if user accepts the agreement, display the fragment for inputing information
4. RequestActivity
#### DATA

The following information will be stored into the default sharedPreference:
**Customer**
- deviceRegistrationId (( TODO ))
- email
- username
- phoneNumber

**Driver**
- deviceRegistrationId (( TODO ))
- email
- username
- phoneNumber
- license

**Comment by byronyi** [comment]
This is resolved in #10.

**Comment by byronyi** [comment]
@ywangbc said he will take this issue as in #10.

That's great. We also need a Welcome screen for <code>MainActivity</code>, with possibly an animation\* to comfort user that waiting for server response. Currently it takes 3~4 s, so I think we should have one.

*Something like <url>http://adverterenbijeisma.nl/wp-content/uploads/2013/02/loading-icon.gif</url>

**Comment by cyw617** [comment]
This has been addressed in Issue #16. Below are just some notes.

### Input Validation and Beautification

#### Names
- cannot be empty (null, white spaces, or tabs)
- can only contain letters and white spaces
- " tiM      wOnG     " (with more than one white space in between) will be converted to "Tim Wong"

#### Phone
- cannot be empty (null, white spaces, or tabs)
- can only contain numbers
- must consist of 8 digits
- must start with "5", "6", or "9" (HK mobile phone no.)
